# -*- mode: org; coding: utf-8-unix; indent-tabs-mode: nil -*-
#+TITLE: ido-mode の設定
#+AUTHOR: Hiroyuki Ono
#+EMAIL: bps@sculd.com
#+LASTUPDATE: 2015-10-23 15:01:45
#+LANG: ja
#+LAYOUT: page
#+CATEGORIES: emacs
#+PERMALINK: config/ag_config.html
* Switch Buffer, ido-mode

http://ergoemacs.org/emacs/emacs_buffer_switching.html

When you call switch-to-buffer 【Ctrl+x b】, emacs prompt you for a name, and you can press Tab ↹ for name completion.

Emacs 22 (released in 2007) has a improved switch buffer command called ido-mode. It will show a list of candidates AUTOMATICALLY as you type (no need to press Tab ↹ first).

Set ido-mode as Default
To make ido-mode default for switching buffer, put the following in your emacs init:

;; make buffer switch command auto suggestions, also for find-file command
#+BEGIN_SRC emacs-lisp
(ido-mode 1)
#+END_SRC
With the above, the command switch-to-buffer 【Ctrl+x b】 will call ido's version.

Make Ido Suggestions Display Vertically

#+BEGIN_SRC emacs-lisp
;; make ido display choices vertically
(setq ido-separator "\n")

;; display any item that contains the chars you typed
(setq ido-enable-flex-matching t)
#+END_SRC

Ido Keybinding

Most useful Ido keybinding:

【→】 → Select the next choice.
【←】 → Select the previous choice.
【↑】 → Go to the buffer you switched to last time. 【↓】 for next.
【Enter ↵】 → Use the first choice.
【Ctrl+f】 → stop suggestion. useful for creating new file. 【Ctrl+b】 to go back to buffer selection mode.
【Ctrl+d】 → switch to open directory mode.
【Ctrl+g】 → cancel.
