#!/bin/bash

if which anyenv >/dev/null 2>&1 && declare -f addpath > /dev/null
then
    if [ -d $HOME/.anyenv ]
    then
        addpath -p PATH $HOME/.anyenv/bin
        eval "$(anyenv init -)"
    fi
    for D in `ls $HOME/.anyenv/envs`
    do
        addpath -p PATH $HOME/.anyenv/envs/$D/shims
    done
fi
